name: yoyo_calculator
description: Yoyo OS Settings

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  bluez: ^0.8.1
  flutter:
    sdk: flutter
  fluent_ui: ^4.3.0
  fluentui_system_icons: ^1.1.190
  safe_change_notifier: ^0.2.0
  udisks: ^0.4.0
  filesize: ^2.0.1
  linux_system_info:
    git:
      url: https://github.com/Yoyo-OS/linux_system_info.git
      ref: master
  provider: ^6.0.5
  system_theme: ^2.1.0
  window_manager: ^0.3.0
  flutter_acrylic: ^1.0.0+2
  math_expressions: ^2.3.1
  hive_flutter: ^1.1.0
  responsive_builder: ^0.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
flutter_intl:  
    enabled: true